### ISSUE TITLE
Error while trying to install mcfly

### ISSUE THREAD

**Issue by simonknutzen88** [NLeSC/mcfly-tutorial#30]
Hello,

I want to start using mcfly but I have problems to install the package. I followed the instruction on the installation page but I get the following error:

C:\Users\KnutzenS>pip install --trusted-host pypi.python.org mcfly
Collecting mcfly
  Downloading mcfly-1.0.1.tar.gz
Requirement already satisfied: matplotlib in c:\users\knutzens\appdata\local\continuum\anaconda3\lib\site-packages (from mcfly)
Requirement already satisfied: numpy in c:\users\knutzens\appdata\local\continuum\anaconda3\lib\site-packages (from mcfly)
Requirement already satisfied: scikit-learn>=0.15.0 in c:\users\knutzens\appdata\local\continuum\anaconda3\lib\site-packages (from mcfly)
Requirement already satisfied: scipy>=0.11 in c:\users\knutzens\appdata\local\continuum\anaconda3\lib\site-packages (from mcfly)
Exception:
Traceback (most recent call last):
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "C:\Users\KnutzenS\AppData\Local\Continuum\Anaconda3\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

I am able to install other packages with pip so I do not think that it's a general problem with pip.
I am using:
- pip 9.0.1
- Python 3.6.3 :: Anaconda, Inc.

**Comment by vincentvanhees** [comment]
hi, we had some issues with windows installation and I vaguely remember that it had to do with Python version. Could you try using Python 3.5? Note also that this is the issue tracker for the mcfly-tutorial repository, not mcfly itself. Posting this issue in https://github.com/NLeSC/mcfly would increase the chance of it being seen.

**Comment by simonknutzen88** [comment]
Hi,
Many thanks for the help. Changing to python 3.5 indeed fixed the problem. :) 
And sorry for posting in the wrong issue tracker...

Cheers,
Simon
